spring:
  application:
    name: EnterpriseDemo
  datasource:
    url: jdbc:postgresql://postgres:5432/enterprise
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver